# Generated by Django 3.1.2 on 2020-12-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramId', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
